version: '3.0'


services:

  angular_learning_zone:
    container_name: learning-zone-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NG_PROJECT_NAME: learning-zone-app
    ports:
      - '8000:80'
